"""
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        mapping = [0] * 26
        for c in s:
            mapping[ord(c) - ord('a')] += 1
        for c in t:
            mapping[ord(c) - ord('a')] -= 1
        for idx, num in enumerate(mapping):
            if num < 0:
                return str(chr(ord('a') + idx))
        return None
